version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "igor-lirussi"
      - "Daniele-Tentoni"
      - "silviazandoli"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "igor-lirussi"
      - "Daniele-Tentoni"
      - "silviazandoli"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "igor-lirussi"
      - "Daniele-Tentoni"
      - "silviazandoli"
