name: Trigger notification sending

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger this workflow each day at midnight.
    - cron: "0 5 * * *" #UTC TIME, Italy is generally +2h

jobs:
  email-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          method: "GET"
          url: "https://weather-vortex-server.herokuapp.com/forecast/notify"
          timeout: 60000
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}

  # Trigger a direct telegram notification.
  # Have to be a http call to our server to trigger notification sending. https://github.com/marketplace/actions/web-request-action
  telegram-notification:
    needs: [email-notifications]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            This is a ${{ github.event_name }} event,
            on github.com/${{ github.repository }}. 
            Is triggered every day at midnight to 
            send notifications to our registered users. 
            Now it remember to make this job working, 
            like a "Remember that you have to die" or similar.
          format: html
          disable_web_page_preview: true
