name: Deploy

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: weather-vortex-server

jobs:
  master-check:
    name: Assure that we are on master branch
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit -1

  Deploy:
    name: Deploy to Heroku paas
    needs: [master-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
          justlogin: true
          # usedocker: true

      - name: Deploy the web dyno
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
          # healthcheck: format("https://{0}.herokuapp.com/health", '${{secrets.HEROKU_APP_NAME}}')
          rollbackonhealthcheckfailed: true
          usedocker: true

  TelegramJobDeploy:
    name: Send Telegram notification on successful workflow
    needs: [Deploy]
    if: "false"
    runs-on: ubuntu-latest
    steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event_name }} event,
            on github.com/${{ github.repository }}, 
            <b>${{ github.event.head_commit.message }}</b>
            ✅ <b>SUCCEDED</b>✅
          format: html
          disable_web_page_preview: true

  TelegramJobFailure:
    name: Send Telegram notification on failure workflow
    needs: [Deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event_name }} event,
            on github.com/${{ github.repository }}, 
            <b>${{ github.event.head_commit.message }}</b>
            ❌ <b>FAILED</b> ❌
          format: html
          disable_web_page_preview: true

  push-to-registry:
    name: Push Docker image to Docker Hub
    needs: [master-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: antonioparolisi/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            antonioparolisi/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }},
            antonioparolisi/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
