name: Deploy to Heroku

on:
  push:
    branches:
      - "main"
    # Ignore paths without code or useful runtime files.
    paths-ignore:
      - "**/*.md"
      - "**/*.data"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
          justlogin: true
          # usedocker: true

      - name: Deploy the web dyno
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
          usedocker: true

  TelegramJobDeploy:
      needs: [Deploy]
      if: success() 
      runs-on: ubuntu-latest
      steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{ github.event_name }} event,
              on github.com/${{ github.repository }}, 
              <b>${{ github.event.head_commit.message }}</b>
              ✅ <b>SUCCEDED</b>✅ 
          format: html
          disable_web_page_preview: true
     
  TelegramJobFailure:
      needs: [Deploy]
      if: failure() 
      runs-on: ubuntu-latest
      steps:
      - name: Send custom Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              ${{ github.event_name }} event,
              on github.com/${{ github.repository }}, 
              <b>${{ github.event.head_commit.message }}</b>
              ❌ <b>FAILED</b> ❌ 
          format: html
          disable_web_page_preview: true
