name: Node Unit Tests

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/*.[mM][dD]"
      - "**/*.[dD][aA][tT][aA]"

jobs:
  build:
    name: Test using Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}

      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1

      - name: Run tests
        run: |
          rm -rf node_modules/ package-lock.json
          npm --version
          npm i
          npm run build --if-present
          npm test
        env:
          NODE_ENV: "test"
          MONGODB_URI: mongodb://localhost:27017/test # Access mongoDB Docker container
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          PWDMAIL: ${{ secrets.PWDMAIL }}
          RESET_PASSWORD_KEY: ${{ secrets.RESET_PASSWORD_KEY }}
          SECRET: ${{ secrets.SECRET }}
          TROPOSPHERE_API_KEY: ${{ secrets.TROPOSPHERE_API_KEY }}
          USEREMAIL: ${{ secrets.USEREMAIL }}
