name: Node Unit Tests

on:
  push:
    branches-ignore:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "**/*.data"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/*.md"
      - "**/*.data"

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          npm --version
          npm ci -f
          npm run build --if-present
          npm test
        env:
          SECRET: ${{ secrets.SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
