name: Node Unit Tests

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/*.md"
      - "**/*.data"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1

      - name: Run tests
        run: |
          npm --version
          npm i
          npm run build --if-present
          npm test
        env:
          NODE_ENV: "test"
          MONGODB_URI: mongodb://localhost:27017/test # Access mongoDB Docker container
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          TROPOSPHERE_API_KEY: ${{ secrets.TROPOSPHERE_API_KEY }}
